### ISSUE TITLE
Android N Preview on Nexus Player specific issues

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#110]
Cumulus TV continually crashes, even when in other apps.  You will get a box that pops up in the middle of the screen telling you that Cumulus TV has crashed, and to either "Restart App", "Provide Feedback" or "Close App".

Aware that Android N may not be supported until release, but figured it may be something worth noting as a bug otherwise.

**Comment by bgiesing** [comment]
Yeah forgot to make an issue but I was sure you had the logs already.

~~Also, do you know how Google is categorizing apps that appear by clicking Get More in the new Live Channels update? I know there's more apps than just Pluto and both HomeRun apps (including yours) Maybe by the manifest calling Live Channels?~~

**Comment by Fleker** [comment]
Yeah I've been getting crash logs. I'll try taking a look at it early next
week.

There's a manifest entry for Live Channels Google can check.

**Comment by Fleker** [comment]
I think this may have been fixed in 1.5.2. Seems like it wasn't completely a bug with Android N.

**Comment by Fleker** [comment]
Does it work on the N preview now?

**Comment by alanmcramer** [comment]
Working for the most part.  Seems to still crash when selecting channel sources via Live Channels app.

**Comment by Fleker** [comment]
@alanmcramer I just pushed an update today. Let me know if that fixes it.

**Comment by bgiesing** [comment]
@Fleker So for me it was working fine.... till I got the update from last night. Now it non-stop crashes inside Live Channels (so much so that if it wasn't for the Launcher recommendations showing another Live channel, I wouldn't have been able to get back in!)

(PS: Speaking of that Live channel, Androidtv.news might want to update the running list with APK links for ToonAft and SplatNR since they got removed from Google Play. Here's where I got them https://www.reddit.com/r/AndroidTV/comments/47t705/toonaftsplatnr_gone/d152rkg)

**Comment by Fleker** [comment]
Crap. Based on the crash logs there's something broken in the latest ExoPlayer dependency. It should be an easy fix though.

**Comment by LinkofHyrule89** [comment]
Has anyone had problems with it complaining you're low on memory on the Nexus Player? My streams seem to stop all the time. Is there a way to force it to pre-buffer the video onto my external flash drive? Is there a way to enable pausing the such on these streams?

**Comment by alanmcramer** [comment]
No issues with Low Memory as such.  I do get buffering issues with my Nexus Player, but figure that is my Wifi, as I get the buffering issues with other apps as well.

**Comment by LinkofHyrule89** [comment]
My Nexus Player is on an Ethernet connection and everything else streams perfectly fine I guess they could just be crappy streams I guess. IDK where to get some good streams at all the sites have streams that are pretty useless.

**Comment by Fleker** [comment]
The issue of necessary bandwidth isn't strictly an issue with Android N, so
I think I can close this.
